### PR TITLE
Fix bug where meta policy engine would not process job updates.

### LINKED ISSUE #15: The nomad-meta-policy-engine is unable to load the policy tags from the job group meta stanza
**Describe the bug**

The nomad-meta-policy-engine is unable to load the policy tags from the meta stanza within the job-group stanza. This is probably happening because `jobs[i].ModifyIndex` is always <= `maxFound (meta.LastIndex)` and so `m.indexHasChange(jobs[i].ModifyIndex, maxFound)` always returns `False` and prevents `m.readJobMeta(jobs[i].ID)` to load policy from the meta tags into memory. (With Nomad version `v0.9.2`; not tested against older nomad versions)

https://github.com/jrasell/sherpa/blob/master/pkg/policy/watcher/watcher.go#L41

**To reproduce**

Run the sherpa server with meta-policy-engine enabled
```
sherpa server --autoscaler-enabled --policy-engine-nomad-meta-enabled --policy-engine-api-enabled=false --log-level=debug
```
and deploy a nomad job where the policy is difined in the group stanza like the following
```
 meta {
      sherpa_enabled = true
      sherpa_max_count = 4
      sherpa_min_count = 1
      sherpa_scale_out_count = 1
      sherpa_scale_in_count = 1
      sherpa_scale_out_cpu_percentage_threshold = 40
      sherpa_scale_out_memory_percentage_threshold =30
      sherpa_scale_in_cpu_percentage_threshold = 20
      sherpa_scale_in_memory_percentage_threshold = 5
    }
```

The server logs show that sherpa isn't able to read in the policies from meta tags

```
6:20PM INF starting HTTP server addr=127.0.0.1:8000
6:20PM INF Sherpa server configuration server={"autoscaler-enabled":true,"autoscaler-evaluation-interval":60,"bind-addr":"127.0.0.1","bind-port":8000,"policy-engine-api-enabled":false,"policy-engine-nomad-meta-enabled":true,"policy-engine-strict-checking-enabled":true,"storage-consul-enabled":false,"storage-consul-path":"sherpa/policies/"} telemetry={"telemetry-statsd-address":"","telemetry-statsite-address":""} tls={"tls-cert-key-path":"","tls-cert-path":""}
6:20PM DBG setting up Nomad client
6:20PM DBG setting up in-memory storage backend
6:20PM DBG setting up Sherpa internal auto-scaling engine
6:20PM DBG setting up HTTP server routes
6:20PM INF mounting route endpoint GetSystemHealth method=GET path=/v1/system/health
6:20PM INF mounting route endpoint GetSystemInfo method=GET path=/v1/system/info
6:20PM INF mounting route endpoint GetSystemMetrics method=GET path=/v1/system/metrics
6:20PM INF mounting route endpoint ScaleOutJobGroup method=PUT path=/v1/scale/out/{job_id}/{group}
6:20PM INF mounting route endpoint ScaleInJobGroup method=PUT path=/v1/scale/in/{job_id}/{group}
6:20PM INF mounting route endpoint GetJobScalingPolicies method=GET path=/v1/policies
6:20PM INF mounting route endpoint GetJobScalingPolicy method=GET path=/v1/policy/{job_id}
6:20PM INF mounting route endpoint GetJobGroupScalingPolicy method=GET path=/v1/policy/{job_id}/{group}
6:20PM INF HTTP server successfully listening addr=127.0.0.1:8000
6:20PM INF starting Sherpa Nomad meta policy engine
6:20PM INF starting Sherpa internal auto-scaling engine
6:20PM DBG meta watcher last index has changed
6:21PM DBG no scaling policies found in storage backend
6:22PM DBG no scaling policies found in storage backend
6:23PM DBG no scaling policies found in storage backend
6:24PM DBG no scaling policies found in storage backend
```
Also, `$ sherpa policy list` doesn't list anything

**Expected behavior**

The autoscale policy should be read from the meta stanza within the job group and running 

`$ sherpa policy list`

should list all the policies that were defined as such

**Environment:**
* Sherpa server information (retrieve with `sherpa system info`):
```
Nomad Address                http://loco:4646
Policy Engine                Nomad Job Group Meta
Policy Storage Backend       In Memory
Internal AutoScaling Engine  true
Strict Policy Checking       true
```
* Sherpa CLI version (retrieve with `sherpa --version`):
```
v0.0.1
```
* Server Operating System/Architecture:
```
macOS Mojave Version 10.14.5 / 64 bit
```
* Sherpa server configuration parameters:
```
sherpa server --autoscaler-enabled --policy-engine-nomad-meta-enabled --policy-engine-api-enabled=false --log-level=debug
```
* Nomad client configuration parameters (if any):
```
(Nomad v0.9.2)
client {
  enabled = true
  options {
    "docker.auth.config" = "/etc/nomad/.docker/config.json"
  }
}
```
* Consul client configuration parameters (if any):
```
Not using Consul backend for meat policy engine
```
**Additional context**

### PR DESCRIPTION
**Pull request by jrasell**
The meta policy watcher was doing an incorrect comparison when
checking whether the modify index on a job specification returned
from the API. Previously it was comparing against the maxfound
which was being set to the Jobs().List() returned meta. This meant
the job modify index would always be <= as it could never be
greater than the value of the API returned meta index.

In addition to fixing the above mentioned bug; this commit adds
some contextual logging around the meta watcher to help identify
any future issues and make operating in this mode easier.

Closes #15

### CODE REVIEW

File: pkg/policy/watcher/watcher.go [hunk 1]
```diff
@@ -42,20 +42,38 @@ func (m *MetaWatcher) Run() {
 			m.logger.Debug().Msg("meta watcher last index has not changed")
 			continue
 		}
+		m.logger.Debug().
+			Uint64("old", q.WaitIndex).
+			Uint64("new", meta.LastIndex).
+			Msg("meta watcher last index has changed")
 
-		m.logger.Debug().Msg("meta watcher last index has changed")
+		// Update our last tracked index on this run to match the meta returned from the API.
```
Comment (jvineet) [inline pkg/policy/watcher/watcher.go]: Looks like we are  updating the `maxfound` for every outer for loop iteration, and also in the inner for loop going over jobs. If the execution goes into the inner for-loop, the `maxfound` may actually decrease in value (also it looks like the `jobs` list is sorted based on the job `ID` instead of job `ModifyIndex`). This will probably result in `q.WaitIndex` to be lower than the one in the meta returned from the API call. That may create some cruft by making redundant api calls that won't block.

 It appears that `q.WaitIndex` and `m.lastChangeIndex` are keeping track of two separate things, so assigning them the sam `maxFound` at the end of the outer for might not be useful. Can we just use the `maxfound` to keep track of the last maximum index that results in loading the job policy params from the meta stanza for a job, and then assign that to `lastChangeIndex` while directly assigning `q.WaitIndex` -> `meta.LastIndex` at the end of the outer for loop.

File: pkg/policy/watcher/watcher.go [hunk 2]
```diff
@@ -42,20 +42,38 @@ func (m *MetaWatcher) Run() {
...
 			}
 
-			maxFound = jobs[i].ModifyIndex
+			m.logger.Debug().
+				Uint64("old", m.lastChangeIndex).
+				Uint64("new", jobs[i].ModifyIndex).
+				Str("job", jobs[i].ID).
+				Msg("job modify index has changed is greater than last recorded")
 
+			maxFound = jobs[i].ModifyIndex
```
Comment (jvineet) [inline pkg/policy/watcher/watcher.go]: probably need to sort job list based on job `ModifyIndex` if we are directly overriding the `maxFound` here

File: pkg/policy/watcher/watcher.go [hunk 3]
```diff
@@ -42,20 +42,38 @@ func (m *MetaWatcher) Run() {
...
 			go m.readJobMeta(jobs[i].ID)
 		}
 
+		// Update the Nomad API wait index to start long polling from the correct point and update
+		// our recorded lastChangeIndex so we have the correct point to use during the next API
+		// return.
 		q.WaitIndex = maxFound
```
Comment (jvineet) [inline pkg/policy/watcher/watcher.go]: perhaps `q.WaitIndex = meta.LastIndex` ?
